apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nmfau5nz3-go 
  janus-idp.io/tekton: nmfau5nz3-go
  backstage.io/kubernetes-id: nmfau5nz3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nmfau5nz3-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml