apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nmfau5nz3-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:ee810324a0f291e1576df5bb17617426c82140f3@sha256:c5e53e3c2d6ba5191a87bd87945021f41b0eee0a9c75fccd7b093e4da98e1750
          name: container-image
